### ISSUE TITLE
Режим калибровки для определения оптимального значения порога

### ISSUE THREAD

**Issue by EvilLord666** [OpticalMeasurementsSystems/2DImageProcessing#14]
В приложение, запускаемое на PS нужно  добавить режим калибровки, для определения наилучшего значения порога.

**Comment by EvilLord666** [comment]
Задана калибровка порога в PS по частоте 0 точки 0, однако, в виду того, что не могу сегодня запуститься (рабочее место занято) на отладку данная задача не проверена (ветка UshakovMV_RegionSelection).

**Comment by EvilLord666** [comment]
Саша, проверь, пожалуйста, работоспособность ветки UshakovMV_RegionSelection.

**Comment by EvilLord666** [comment]
Проверил под отладкой, к сожалению, без лазера, алгоритм калибровки работает. Для достоверности необходимо проверять с лазером.

**Comment by stdstring** [comment]
К сожалению, работает или к сожалению, без лазера? )))

**Comment by EvilLord666** [comment]
Работает без лазера, лазер одолжил Юрий, поэтому я не могу пока проверить калибровку порога.

**Comment by EvilLord666** [comment]
Проект заморожен, задача прекращается в связи со сворачиванием 218-го.
