### ISSUE TITLE
Сбор значений множества пикселей для усреднения

### ISSUE THREAD

**Issue by Elesv** [OpticalMeasurementsSystems/2DImageProcessing#15]
Необходимо реализовать алгоритм фильтрации (калибровки на лету).

Суть задачи заключается в сборе значений нескольких рядом стоящих пикселей, усреднении этих значений и выставлении порогов девиации относительно усредненных значений.

**Comment by EvilLord666** [comment]
Проект заморожен, задача прекращается в связи со сворачиванием 218-го.
