### ISSUE TITLE
Способы анализа частот

### ISSUE THREAD

**Issue by EvilLord666** [OpticalMeasurementsSystems/2DImageProcessing#17]
Поскольку случай у нас специфический, алгоритмы анализа изображений по образцу нам не подходят ( у нас относительно мало точек за 500 мкс), поэтому придется сочинять что-то самим. Я думаю, что можно сделать следующее:
по сути нам нужно одну точку, где частота перепрыгнула и если верить таблице с отклонениями и картике с разверткой, то при работе в той области поля управления у нас нет частот f4 и f2 (хотя с может быть и не так понял,может это только пример). По-хорошему, погрешность нужно уменьшить, может быть получится ее уменьшить взяв несколько периодов и поделить на число периодов (но данное предложение не учитывает зависимость от начальной фазы сигнала). Зависимость от фазы можно прикинуть написав консольное приложение на С++ и взять стартовую точку в начале, в середине и в конце полупериода 0 и 1 и посчитать даст ли нам такая математика что-то или нет. Но опять же поскольку в ПЛИС очень плохо с делением, то брать можно только число периодов степени двойки т.е. 1,2,4 или 8. Пока больше особых предложений нет.  И еще один момент, давайте считать все для текущего случая для ридаута в 21 мкс.

**Comment by Elesv** [comment]
Поскольку мы имеем дело с тривиальной световой пульсацией "перепрыгивающей" с одной частоты на другую спектральный анализ посредством Фурье кажется нецелесообразным по следующим причинам:

1. Отсутствие данных для проведения анализа. В виду отсутствия корреляции между пульсациями на разных частотах не представляется возможным воспринимать их в виде единого сигнала. Безусловно, обладая всеми необходимыми характеристиками пульсации мы могли бы реставрировать(выровнять интервалы между вспышками и сами вспышки по продолжительности, устранить коллизии) и реконструировать(синтезировать) единый сигнал во временной области, затем преобразовать его к представлению в частотной области(получить спектр) и анализировать. Однако, учитывая тот факт, что наличие, либо отсутствие посторонней пульсации становится очевидно просто сравнив продолжительность интервалов и/или вспышек, все вышеперечисленные манипуляции теряют какой-либо практический смысл.

2. Отсутствие возможности хранения семплов на ПЛИС. У нас не хватит ресурсов.

3. Передача семплов процессору(если бы мы решили пойти таким путем) породит латентность которая не позволит нам закончить обработку за отведенное время.

**Comment by shrtique** [comment]
@EvilLord666 Мне казалось, что мы уже довольно четко сформулировали задачу...
Повторю еще раз:
На данный мы считаем, что у нас **12** точек измерения! Драгстеры стоят перекрестьем перпендикулярно друг другу, соосно горизонтальной и вертикальной оси соответственно.
От центра мы измеряем по 3 точки по всем четырем направлениям (вверх, вниз, вправо, влево). Соответственно точек у нас **12**!

В каждом из четырех направлений находятся свои пары частот:
Вверх: f5, f3
Вниз: f5, f4
Влево: f5, f1
Вправо: f5, f2

В зависимости от удаленности точки от центра увеличивается время действия частоты отличной от f5.

Вы имеете точно такие же исходные данные, что и я. И меня удивляет, почему, спустя год, мне приходится заново разжевывать вам задачу.


@VeryNiceGuy 

> Отсутствие данных для проведения анализа.

---Что это значит? Каких данных? Изъясняйтесь конкретно!

> В виду отсутствия корреляции между пульсациями на разных частотах не представляется возможным воспринимать их в виде единого сигнала. 

---При чем здесь корреляция между сигналами? Объясните, что вы вкладываете в это понятие и как оно связано с нашим конкретным случаем? 
Идет последовательность импульсов одной частоты, в определенный момент времени начинают приходить импульсы другой частоты. Любая манипуляция (дискретная модуляция сигнала) неизбежно связана с разрывом фазы, т.к. изменения фазы имеют лишь дискретные значения! И вы утверждаете, что такие сигналы нельзя подвергать Фурье анализу?

> Безусловно, обладая всеми необходимыми характеристиками пульсации мы могли бы реставрировать(выровнять интервалы между вспышками и сами вспышки по продолжительности, устранить коллизии) и реконструировать(синтезировать) единый сигнал во временной области, затем преобразовать его к представлению в частотной области(получить спектр) и анализировать.
 
---Интервалы между вспышками? Вы сами понимаете, о чем говорите? У нас жестко заданный паттерн (риски на прозрачном диске), у каждой области риски идут с определенной частотой, частоты эти указаны в документации и показана их погрешность.

>  Однако, учитывая тот факт, что наличие, либо отсутствие посторонней пульсации становится очевидно просто сравнив продолжительность интервалов и/или вспышек, все вышеперечисленные манипуляции теряют какой-либо практический смысл.

---Прочитайте свое предложение и переформулируйте его. Смысл предложения не ясен.

> Отсутствие возможности хранения семплов на ПЛИС. У нас не хватит ресурсов.

---На основе чего вы сделали такой вывод? Если вы так считаете, приведите калькуляцию.
Я работаю точно с таким же кристаллом как и вы. У меня производится обработка изображения с разрешением 1280х1024 8bit. BlockRAM и LUTRAM задействованы на 16-18%.... не говоря уже у том, что в качестве буфера вы можете использовать DDR3, который подключен через процессор.

> Передача семплов процессору(если бы мы решили пойти таким путем) породит латентность которая не позволит нам закончить обработку за отведенное время.

---Вопрос тот же: на основе чего сделан такой вывод? Учитесь обосновывать свое мнение.


И так, подытожим:

Вас рекомендовали как профессионалов, но вы не показываете должного уровня. Кодить, без вдумчивого анализа задачи и без проработки различных вариантов решения задачи это не уровень профессионалов.

Мы договорились с вами, что в пн будет обзор по различным путям решения. По итогу вы оба мне прислали отписку, для формулирования которой нужно порядка 3ех минут. Где **КОНКРЕТНОЕ** предложение/алгоритм/направление исследования решения задачи??? Вы оба налили **ВОДЫ** и ни одного конкретного предложения.

Проект, который вы выполняете, это не научная отписка, в которой вы создаете вид бурной деятельности! Я с вами пытаюсь работать на основе хороших человеческих отношений. Но вы этим отношением пренебрегаете. В таком русле продолжать взаимодействие нецелесообразно.

@VeryNiceGuy Изъясняйтесь лаконичным языком, не нужно лить воду. Мы пишем не сочинение пишем, а решаем конкретные инженерные задачи.

@EvilLord666 Я описал вам задачу еще раз. Какие вопросы остались? Частоты вам даны, принцип работы изложен, частотные хар-ки с нашей стороны вам известны. Я жду от вас поиска и разработки конкретных решений!

**Comment by EvilLord666** [comment]
АЛГОРИТМ №1 (Рабоче-крестьянский)
Во многих статьях пишут, что чем меньше сложных дейтсвий в алгоритме, тем лучше, поэтому самый, наверное, простой алгоритм.

На Dragster у нас имеется по 6 точек, поэтому при проходе линейки получаем следущее (псевдокод)

for(для каждой точки)    // 0..5
{
      if(первый запуск)     //  самое начало 500мкс цикла
           фаза = нач._фаза
      else
      {
           while(!прыжок_частоты)
           {
               for(half_period = 0; half_period <=1; half_period++)
               {
                  while(текущая_фаза == фаза || interrupt); //ждем или ожидание прерывается
                  // произошел скачок фиксируем полупериод
                  число_тиков_периода += счетчик; // просуммировали полупериод
                  текущая_фаза = фаза
                  if(!check_half_period(счетчик)) // проверяем число тиков полупериода на 
                                                                    // грубое соответсвие и устанавливаем special_case
                                                                    // когда у нас перекрытие единиц или нулей
                  {
                       прыжок_частоты = true;
                       break;
                  }
                  if(special_case)
                  {
                       прыжок_частоты = true;
                  }
                  if(half_period == 1)
                  {
                       число_тиков += число_тиков_периода;
                       счетчик_периодов++
                       check_period(число_тиков)
                  }
               }
               if(число периодов in (2,4,8)
               {
                    среднее_число_тиков_за_период = число_тиков / число периодов;
                    // усреднение нужно для возможного уменьшения среднего 
                    // зафиксированного числа тиков для уменьшения площади перекрытия 
                    // числа тиков +- ридаут для двух разных частот, но чтобы оценить как это 
                    // дейтсивтельно работает нужно посчитать (см. первый пост)

               }
          }
      }
     if(прыжок_частоты)
     {
          индекс_ожидаемой_чатоты ++;    // но проверку также необходимо сделать, 
                                                                  // это значение не может быть больше 1
         // все теперь можем дальше ничего не считать, т.к. общее число тиков нам известно
     }
}

Т.е. вся идея паттерна это поиск прыжка частоты, может быть 2 варианта:

1. Переход в новую частоту на противоположной фазе, например, 0 частоы 0 в 1 частоты 1
2. Переход на новую частоту в той же фазе длинная 1 (длинного 0, по-моему, не существует).

При этом аккумулируя периоды одной частоты мы проводим вычисления среднего числа тиков периода данной частоты и это среднее значение используем (если оно вычислено) для сравнения с числом тиков полупериода  или периода другой частоты, среднее значение нам теоретически может дать уменьшение числа импульсов и передвижение в область близкую к центру погрешности т.е. к readout/2 (но это еще необходимо посчитать). Но в условиях таких погрешностей, для диска курса все может быть неплохо, а для тангажа могут быть проблемы (большое перекрытие).

**Comment by Elesv** [comment]
`timescale 1 ns / 1 ps

    module frequency_jump_detector #
    (
        parameter pixel_number = 0,
        parameter period_1, /* нс */
        parameter period_2, /* нс */
        parameter period_3, /* нс */
        parameter tolerance /* нс */
    )
    (
        input wire pixel_clock,
        input wire reset,
        input wire enable,
        output wire jump_detected,
        input wire lval,
        input wire[7:0] pixel
    );

    localparam period_50MHz = 20;
    reg[11:0] pixel_counter;
    reg measure_time;
    reg[31:0] elapsed_time;

    reg[1:0] current_frequency;
    localparam FREQUENCY_UNKNOWN = 2'b00;
    localparam FREQUENCY_1 = 2'b01;
    localparam FREQUENCY_2 = 2'b10;
    localparam FREQUENCY_3 = 2'b11;

    always@(posedge pixel_clock) begin
        if(!reset) begin
            pixel_counter <= 0;
            measure_time <= 1'b0;
            elapsed_time <= 0;
            current_frequency <= FREQUENCY_UNKNOWN;
        end
    
        else begin
            if(enable) begin
                if(lval) begin
                    pixel_counter <= pixel_counter + 1;
                
                    if(measure_time)
                        elapsed_time <= elapsed_time + period_50MHz;
                
                    if(pixel_counter == pixel_number) begin
                        if(pixel != 0) begin
                            if(!measure_time) begin
                                measure_time <= 1'b1;
                                elapsed_time <= elapsed_time + period_50MHz;
                            end
                        
                            else begin
                                /* Сбрасываем время. */
                                elapsed_time <= 0;
						
				/* Время между импульсами приблизительно соответствует периоду частоты 1. */
                                if(elapsed_time >= period_1 - tolerance && elapsed_time <= period_1 + tolerance) begin
                                    if(current_frequency != FREQUENCY_UNKNOWN && current_frequency != FREQUENCY_1)
                                        jump_detected <= 1'b1;
                                    
                                    current_frequency <= FREQUENCY_1;
                                end
                            
                            /* Время между импульсами приблизительно соответствует периоду частоты 2. */
                            else if(elapsed_time >= period_2 - tolerance && elapsed_time <= period_2 + tolerance) begin
                                if(current_frequency != FREQUENCY_UNKNOWN && current_frequency != FREQUENCY_2)
                                    jump_detected <= 1'b1;

                                current_frequency <= FREQUENCY_2;                               
                            end
                            
                            /* Время между импульсами приблизительно соответствует периоду частоты 3. */
                            else if(elapsed_time >= period_3 - tolerance && elapsed_time <= period_3 + tolerance) begin
                                if(current_frequency != FREQUENCY_UNKNOWN && current_frequency != FREQUENCY_3)
                                    jump_detected <= 1'b1;
                            
                                current_frequency <= FREQUENCY_3;
                            end
                            
                            /* Промежуток оказался слишком коротким, либо длинным. */
                            /* else begin
                                    jump_detected <= 1'b1;
                                    current_frequency <= FREQUENCY_UNKNOWN;
                                end
                            */
                            end
                        end
                    end
                
                    else begin
                        jump_detected <= 1'b0;
                    end
                end
            
                else begin
                    pixel_counter <= 0;
                end
            end
        end
    end

    endmodule

**Comment by Elesv** [comment]
Алгоритм замеряет время прошедшее с момента регистрации последнего импульса и сравнивает его с периодами заданных частот + допуск. В случае прыжка или ошибки просто еще раз считаем время начиная с проблемного импульса до следующего за ним. Как только частота стабилизируется, она фиксируется и сопоставляется с той что была зарегистрирована ранее.

1. Определяем текущую частоту (полагаю, опорную).
2. Проверяем каждый промежуток между импульсами и ждем прыжок.
3. Пытаемся фиксировать прыжок.
4. В случае неудачи замеряем следующий интервал, определяем текущую частоту и фиксируем прыжок.

**Comment by EvilLord666** [comment]
Я тут провел расчеты на бумаге, оказывается все может быть еще проще. В принципе с такой системой мы не сможем мерять частоту, нам даже не надо считать тики, это бесполезно, т.к. наш дискрет времени - 21мкс, но мы может отличить 21 кГц на фоне 15 или даже 18 за счет дискретности, см. файлы:
![p_20170816_010604](https://user-images.githubusercontent.com/18068522/29334337-e3ac6454-8228-11e7-9016-dba434fff3de.jpg)
![p_20170816_010616](https://user-images.githubusercontent.com/18068522/29334340-e3b810c4-8228-11e7-9b65-e5774082d961.jpg)
![p_20170816_010622](https://user-images.githubusercontent.com/18068522/29334338-e3b1bbc0-8228-11e7-94d2-6a5413b3c957.jpg)

9 кГц -> 5-6 ридаутов на период
13 кГц -> 4-5 ридаутов
15 и 18 - 3-4 ридаута
21 - 2 ридаута
(см. картинки)
Причем точность выше при расчете на период нежели чем на половину периода (вот в чем одна из проблем сейчас). Нам нужно считать число ридаутов за период (т.е. двойное изменение уровня по сравнению с порогом). Случай когда точка из пары 15,21 или 21,18 нужно взять периода 4 и сравнить длительности, если число ридаутов == 2 то мы нашли 21 кГц (их конечно может и 3 , но тогда надо брать соседний, потому что если смотреть рисунок, то после 3х ридаутов для 21кГц сразу идет 2).

**Comment by EvilLord666** [comment]
Анализ перехода 21 кГц в 18 кГц (как самого трудного):
![p_20170820_231413](https://user-images.githubusercontent.com/18068522/29497231-6c0004ba-8606-11e7-8ffa-e8cafbcc72ea.jpg)

**Comment by EvilLord666** [comment]
Проект заморожен, задача прекращается в связи со сворачиванием 218-го.
