### ISSUE TITLE
Time constraints (Временные ограничения)

### ISSUE THREAD

**Issue by Elesv** [OpticalMeasurementsSystems/2DImageProcessing#5]
Необходимо создать набор временных ограничений для всего проекта. Думаю, что-то мы можем позаимствовать из ImageCaptureSystem.

**Comment by EvilLord666** [comment]
Тайминги все выполняются при 50 МГц PIXEL_CLOCK и 100 МГц Fabric. Убрал input и output задержки, они явно не должны быть относительно клоков (возможно, позже мы их вернем)
