### ISSUE TITLE
Точность анализатора частот

### ISSUE THREAD

**Issue by EvilLord666** [OpticalMeasurementsSystems/2DImageProcessing#8]
В процессе работы мы оцениваем частоты из диапазона 9-20 кГц, время сканирования линейки на 50Мгц - 20нс * 1024 = 20,48мкс, соответственно это время и является погрешностью при измерении отдельного пикселя, что является большой проблемой. т.к. при такой погрешности измерение частот это большой вопрос.

**Comment by stdstring** [comment]
Нам нужно уменьшить время сканирования. Варианты следующие (что очевидно): увеличить частоту, распараллелить сканирование (очевидно, что теоретически сканирование распараллеливается очень хорошо). Соответственно, нужно ответить на три вопроса: можно ли увеличить частоту (и, если да, то до какого значения), можно ли распараллелить процесс сканирования (и если да, то на сколько параллельных процессов) и можно ли сделать это все вместе. После этого уже можно выбрать наиболее оптимальную (по сложности и времени реализации) стратегию.

**Comment by EvilLord666** [comment]
Теоретически если заставить работать Dragster на 100 МГц, то время сканирования будет 10,24 мкс. Распараллелить, боюсь, что не получится т.к. Dragster последовательно проводит преобразования на каждом пикселе. По самой задаче нам нужно всего 3 пикселя в начале, в середине и в конце.  Теоретически можно сканировать несколько пикселей, чтобы чаще апдэйтить сканируемые частотным анализатором значения.

**Comment by stdstring** [comment]
А если нужны всего 3 пикселя, то зачем сканировать всю линейку? А почему не получится распараллелить: насколько я помню у вас же несколько Dragster'ов на плате и несколько ядер у процессора? Или я неправильно помню?

**Comment by EvilLord666** [comment]
Каждый Dragster это независимый канал, а сам Dragster устроен так, что он последовательно проходит каждый пиксель

**Comment by stdstring** [comment]
Т.е. я правильно понимаю, что драгстер не умеет смещаться к произвольному пикселю? Другими словами, если мне нужен пиксель номер 100, то я его получу только после того, как считаю пиксели с номерами от 1 до 99? Если так, то такое поведение драгстера жестко задано и никак нельзя его изменить? А нельзя ли натравить на цепочку пикселей, например, 2 драгстера, причем один смещен относительно другого на N / 2 пикселей, где N - длина цепочки (это бы позволило распараллелить процесс)?
И, наконец, насколько сложно поднять частоту работы драгстера до 100 Мгц (или выше, если нужна большая точность)?

**Comment by EvilLord666** [comment]
Да, драгстер не умеет так делать, у нас в схеме жестко 2 драгстера и каждый из них это независимый канал сканирования. 100 МГц это потолок, который заявлен самими производителями, причем не в оф. даташите.

**Comment by stdstring** [comment]
Можно ли в таком случае поделить цепочку пикселей между двумя драгстерами, чтобы каждый из них сканировал свои полцепочки?

**Comment by EvilLord666** [comment]
Думаю, что нужно увеличить частоту до максимальной (80 МГц гарантировано, но может быть будет работать и при 100 МГц), также, возможно получится организовать произвольное считывание определенных пикселей.

**Comment by EvilLord666** [comment]
Согласно FAQ: http://cmosis-support.com/index.php?pg=kb.page&id=72

Для 8 бит и 100 МГц мы можем достичь 95057 сканирований в секунду (почти 100 кГц), это означает, что частоту в 20кГц мы будем измерять с погрешностью +-20%.

**Comment by EvilLord666** [comment]
Правда можно еще поставить Companding Mode, который ускоряет работу (таблица дана для 12 бит) в 4 раза.
